spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service-service.default.svc.cluster.local:8080
          predicates:
            - Path=/api/v1/residents/**, /api/v1/admin/residents/**, /api/v1/services/**, /api/v1/admin/services/**, /api/v1/admin/moderators/**, /api/v1/analysts/**, /api/v1/admin/analysts/**, /api/v1/employees/**, /api/v1/departments/**, /api/v1/admin/moderators/**
        - id: issue-service
          uri: http://issue-service-service.default.svc.cluster.local:8080
          predicates:
            - Path=/api/v1/issues/**, /api/v1/admin/issues/**, /api/v1/categories/**, /api/v1/admin/categories/**, /api/v1/reservations/**, /api/v1/solutions/**
        - id: notification-service
          uri: http://notification-service-service.default.svc.cluster.local:8080
          predicates:
            - Path=/api/v1/notifications/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
            allowedHeaders:
              - Origin
              - X-Auth-Token
              - Content-Type
              - Accept
              - Authorization
server:
  port: 8080