spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service-service.default.svc.cluster.local:8080
          predicates:
            - Path=/api/v1/users/**, /api/v1/residents/**, /api/v1/services/**, /api/v1/moderators/**, /api/v1/analysts/**, /api/v1/employees/**
        - id: issue-service
          uri: http://issue-service-service.default.svc.cluster.local:8080
          predicates:
            - Path=/api/v1/issues/**, /api/v1/categories/**
        - id: notification-service
          uri: http://notification-service-service.default.svc.cluster.local:8080
          predicates:
            - Path=/api/v1/notifications/**
server:
  port: 8080